name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- feature/*
- release/*
- hotfix/*
- bugfix/*
- develop
- master

variables:
- ${{ if or( startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/bugfix/')) }}:
  - group: development
- ${{ if or( eq(variables['Build.SourceBranch'], 'refs/heads/develop'),startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
  - group: staging
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - group: production

resources:
  repositories:
  - repository: AngularTemplate
    type: git
    name: BP-DevOps-Infrastructure/common-pipeline-template-aks
    ref: refs/heads/feature/ncd2

extends:
  template: javascript/angular/yarn/init_Design_System.yml@AngularTemplate
